apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-checkout-task
spec:
  params:
    - name: repo-url
      type: string
      default: "https://github.com/azamd/ez-learning.git"
    - name: branch
      type: string
      default: "master"
  steps:
    - name: git-checkout
      image: alpine/git
      script: |
        git clone $(params.repo-url) --branch $(params.branch)
