apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    openshift.io/installed-from: tektonhub
    tekton.dev/categories: Security
    tekton.dev/displayName: grype
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: 'linux/amd64,linux/arm64'
    tekton.dev/tags: 'CLI, grype'
  name: grype
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/installed-from': {}
            'f:tekton.dev/categories': {}
            'f:tekton.dev/displayName': {}
            'f:tekton.dev/pipelines.minVersion': {}
            'f:tekton.dev/platforms': {}
            'f:tekton.dev/tags': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/version': {}
        'f:spec':
          .: {}
          'f:description': {}
          'f:params': {}
          'f:steps': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
  namespace: medaziz-amdouni-dev
  labels:
    app.kubernetes.io/version: '0.1'
spec:
  description: >-
    A vulnerability scanner for container images and filesystems. Works with
    Syft, the powerful SBOM (software bill of materials) tool for container
    images and filesystems.
  params:
    - description: The Arguments to be passed to Grype command.
      name: ARGS
      type: array
    - default: >-
        docker.io/anchore/grype@sha256:40c41e43eff0eb979375ea705f0cf5f6f698941099f63c890c3eb90b6ef72db5
      description: Grype image to be used
      name: GRYPE_IMAGE
      type: string
  steps:
    - args:
        - $(params.ARGS)
      image: $(params.GRYPE_IMAGE)
      name: grype
      resources: {}
      workingDir: $(workspaces.source-dir.path)
  workspaces:
    - name: source-dir
      optional: true
