apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: semgrep-analysis
spec:
  params:
    - description: path to the repo to be scanned.
      name: repo_path
      type: string
    - default: .
      description: The context directory within the repository.
      name: CONTEXT_DIR
      type: string
  steps:
    - image: 'docker.io/returntocorp/semgrep:latest'
      name: sca-with-semgrep
      resources: {}
      script: |
        #!/bin/bash
        cd $(workspaces.source.path)/$(params.CONTEXT_DIR)
        semgrep scan ci
        workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
  workspaces:
    - description: A workspace that contains fetched git repo.
      name: source
