version: "3.8"

services:

  mariadb:
    container_name: mariadb-container
    image: mariadb:latest
    networks:
      - ez-network
    ports: 
     - '3306:3306'
    volumes: 
     - data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MARIADB_PORT_NUMBER: 3306
      MARIADB_USER: user1
      MARIADB_PASSWORD: pass1
      MARIADB_ROOT_PASSWORD: pass1
      MARIADB_DATABASE: somedb

  app:
    container_name: ez-learning_spring
    depends_on:
      - mariadb
    links:
      - mariadb:somedb
    image: amdaziz/ez-learning:latest
    restart: on-failure
    ports:
        - '8080:8080'
    networks:
      - ez-network
    environment:
      MARIADB_HOST: mariadb
      MARIADB_PORT_NUMBER: 3306
      MARIADB_USER: user1
      MARIADB_PASSWORD: pass1
      MARIADB_DATABASE: somedb
      APP_PROFILE: prod

networks:
  ez-network:
    name: ez-network
volumes:
  data: {}
