version: "3.8"

services:

  mariadb:
    container_name: mdb-container
    image: mariadb:latest
    networks:
      - ez-network
    ports: 
     - '3306:3306'
    volumes: 
     - data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MARIADB_PORT_NUMBER: 3306
      MARIADB_USER: root
      MARIADB_PASSWORD: 
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: somedb

  app:
    container_name: ez-learning_spring
    depends_on:
      - mariadb
    image: amdaziz/ez-learning:latest
    restart: on-failure
    ports:
        - '8080:8080'
    networks:
      - ez-network
    environment:
      MARIADB_HOST: mariadb
      MARIADB_PORT_NUMBER: 3306
      MARIADB_USER: root
      MARIADB_PASSWORD: 
      MARIADB_DATABASE: somedb
      APP_PROFILE: prod

networks:
  ez-network:
    name: ez-network
volumes:
  data: {}
