kind: Service
apiVersion: v1
metadata:
  name: ez-learning-svc
  namespace: amd-med-aziz-dev
spec:
  clusterIP: 172.30.156.229
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.156.229
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: ez-learning-git
    deployment: ez-learning-dep
status:
  loadBalancer: {}
