kind: ConfigMap
apiVersion: v1
metadata:
  name: ez-learning-env-cm
  namespace: amd-med-aziz-dev
data:
  APP_PROFILE: dev
  MYSQL_DATABASE: sampledb
  MYSQL_HOST: mariadb
  MYSQL_PASSWORD: 1PxBIR2V4M15d8x37
  MYSQL_PORT_NUMBER: '3306'
  MYSQL_ROOT_PASSWORD: vdrYMMTAQDglVuOSK
  MYSQL_USER: AmdMedAziz
