scrape_configs:
  - job_name: 'Ez-Learning Application Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['192.168.1.12:8080']
        labels:
          application: 'Ez-Learning Web Application'